export const BEGIN_DRAG = 'BEGIN_DRAG'
export const END_DRAG = 'END_DRAG'
export const DROP = 'DROP'
export const HOVER = 'HOVER'
export const ENTER = 'ENTER'
export const LEAVE = 'LEAVE'
export const CAN_DRAG = 'CAN_DRAG'
export const CAN_DROP = 'CAN_DROP'
